In [1]:
import numpy as np

## Data types and Attribute

In [ ]:
# a1- 1d  array, vector
# a2- 1d array, matrix
# a3- 1d array, matrix

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [21]:
a2 = np.array([[1,2.5,3],
             [4.01,5,6]])
a2

array([[1.  , 2.5 , 3.  ],
       [4.01, 5.  , 6.  ]])

In [22]:
a3= np.array([[[1,2,3],
             [4,5,6]],
             [[7,8,9],
             [10,11,12]],
               [[13,14,15],
             [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [23]:
a1.shape

(3,)

In [24]:
a2.shape

(2, 3)

In [25]:
#z,x,y
a3.shape

(3, 2, 3)

In [26]:
#ndim => number of dimensions a1=>1D, a2=>2D, a3=3D
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [27]:
a4= np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
             [[10,11,12],
               [13,14,15],
             [16,17,18]]])
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [14]:
a4.ndim

3

In [17]:
a4.shape

(2, 3, 3)

In [28]:
a1.dtype,a2.dtype,a3.dtype,a4.dtype

(dtype('int32'), dtype('float64'), dtype('int32'), dtype('int32'))

In [30]:
#total values (no of elements)
a1.size,a2.size,a3.size,a4.size

(3, 6, 18, 18)

In [32]:
type(a1),type(a2),type(a3),type(a4)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [33]:
# create a dataframe from numpy array
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.00  2.5  3.0
1  4.01  5.0  6.0

In [34]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [35]:
sample_array.dtype

dtype('int32')

## Creating arrays
# shift+tab=> click in between brackets like ones()
ones = np.ones((2,3))


In [37]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [39]:
ones.dtype, type(ones)

(dtype('float64'), numpy.ndarray)

In [41]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
range_array= np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [49]:
random_array= np.random.randint(0,10, size=(3,5))
random_array

array([[4, 6, 9, 6, 4],
       [7, 9, 7, 3, 3],
       [4, 7, 9, 6, 0]])

In [50]:
random_array.size, random_array.shape, type(random_array)

(15, (3, 5), numpy.ndarray)

In [51]:
random_array= np.random.randint(0,10, size=(2,3,5))
random_array

array([[[0, 9, 7, 0, 2],
        [5, 4, 6, 2, 1],
        [0, 4, 4, 7, 8]],

       [[7, 3, 1, 3, 6],
        [5, 7, 0, 8, 8],
        [5, 3, 8, 4, 0]]])

In [55]:
random_array_2=np.random.random((5,3))
random_array_2, random_array_2.shape, type(random_array_2)

(array([[0.85180514, 0.4420263 , 0.4632416 ],
        [0.84718055, 0.15134973, 0.78026952],
        [0.66693785, 0.52139396, 0.86424822],
        [0.75994266, 0.64991623, 0.81724866],
        [0.54023607, 0.06666535, 0.56564946]]),
 (5, 3),
 numpy.ndarray)

In [57]:
random_array_3=np.random.rand(5,3)
random_array_3

array([[0.52333521, 0.07699468, 0.10878966],
       [0.66836074, 0.88875592, 0.82912762],
       [0.07650593, 0.78884946, 0.74027647],
       [0.06829704, 0.29834622, 0.44585032],
       [0.91566387, 0.70386684, 0.10767349]])

In [83]:
#pseudo-random numbers
np.random.seed(seed=0)    #doesnt allow to change randomly gives same values all the time, seed=0,1,2-----9999
random_array_4=np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [77]:
random_array_5=np.random.random((5,3))
random_array_5

array([[0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561],
       [0.77423369, 0.45615033, 0.56843395],
       [0.0187898 , 0.6176355 , 0.61209572],
       [0.616934  , 0.94374808, 0.6818203 ]])

## view arrays and matrixes

In [84]:
#tells unique values
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1.  , 2.5 , 3.  ],
        [4.01, 5.  , 6.  ]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]]))

In [86]:
a1[0]

1

In [89]:
a2[0,1], a2[0]

(2.5, array([1. , 2.5, 3. ]))

In [88]:
a3[1,1,1]

11

In [92]:
a1[:2], a2[:2,:1],a3[:2,:2,:2]

(array([1, 2]),
 array([[1.  ],
        [4.01]]),
 array([[[ 1,  2],
         [ 4,  5]],
 
        [[ 7,  8],
         [10, 11]]]))

In [93]:
a3[:,:,:1]

array([[[ 1],
        [ 4]],

       [[ 7],
        [10]],

       [[13],
        [16]]])

## manipulate and comparing array

## arithmetic

In [95]:
a1

array([1, 2, 3])

In [96]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [97]:
# +,-,*,/,//,%,**,  ** or np.square(a1),   exp(a1), log(a1)
a1 + ones      # np.add(a1,ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

In [98]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [99]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [100]:
a2

array([[1.  , 2.5 , 3.  ],
       [4.01, 5.  , 6.  ]])

In [101]:
a1 * a2

array([[ 1.  ,  5.  ,  9.  ],
       [ 4.01, 10.  , 18.  ]])

In [108]:
a3, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]]),
 (3, 2, 3))

In [103]:
a2 * a3

array([[[  1.  ,   5.  ,   9.  ],
        [ 16.04,  25.  ,  36.  ]],

       [[  7.  ,  20.  ,  27.  ],
        [ 40.1 ,  55.  ,  72.  ]],

       [[ 13.  ,  35.  ,  45.  ],
        [ 64.16,  85.  , 108.  ]]])

In [105]:
# reshape numpy array
a_1 = np.array([1, 2, 3, 4, 5, 6])
a_1

array([1, 2, 3, 4, 5, 6])

In [110]:
a_2 = a_1.reshape((2,3))
a_2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a_1 * a3 # so we need to reshape 

## aggregation
aggregation =performing same operations on a number of things

In [121]:
listy_list = [1,2,3]
type(listy_list)

list

In [120]:
sum(a1)

6

In [123]:
np.sum(a1)

6

In [117]:
%timeit sum(listy_list)
%timeit np.sum(a1)       #much faster than python sum() function

161 ns ± 4.94 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
5.66 µs ± 246 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [124]:
a2

array([[1.  , 2.5 , 3.  ],
       [4.01, 5.  , 6.  ]])

In [328]:
np.mean(a2), np.var(a2)          #max,min,std,var

(3.5849999999999995, 2.7027916666666667)

In [127]:
# std=squareroot of var
np.sqrt(np.var(a2))

1.6440169301642447

In [132]:
# variance, standard deviation

# reshape and transpose

In [165]:
a2

array([[1.  , 2.5 , 3.  ],
       [4.01, 5.  , 6.  ]])

In [166]:
a2.shape

(2, 3)

In [140]:
a4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [141]:
a4.shape

(2, 3, 3)

In [142]:
a2*a4

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [167]:
a2, a2.shape

(array([[1.  , 2.5 , 3.  ],
        [4.01, 5.  , 6.  ]]),
 (2, 3))

In [168]:
a2

array([[1.  , 2.5 , 3.  ],
       [4.01, 5.  , 6.  ]])

In [169]:
a2.reshape(2,3,1).shape

(2, 3, 1)

In [170]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1.  ],
        [2.5 ],
        [3.  ]],

       [[4.01],
        [5.  ],
        [6.  ]]])

In [171]:
a2_reshape * a4

array([[[  1.  ,   2.  ,   3.  ],
        [ 10.  ,  12.5 ,  15.  ],
        [ 21.  ,  24.  ,  27.  ]],

       [[ 40.1 ,  44.11,  48.12],
        [ 65.  ,  70.  ,  75.  ],
        [ 96.  , 102.  , 108.  ]]])

In [187]:
# transpose-> switches the axix'
a2.T

array([[1.  , 4.01],
       [2.5 , 5.  ],
       [3.  , 6.  ]])

In [188]:
a2.T.shape

(3, 2)

In [189]:
a4.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [190]:
a4.T.shape

(3, 3, 2)

## DOT PRODUCT
another wayof finding patterns btw 2 diff set of numbers

In [199]:
np.random.seed(0)
mat1=np.random.randint(10, size=(5,3))
mat2=np.random.randint(10, size=(5,3))
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [200]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [201]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [204]:
#element wise multiplications (HADAMARD PRODUCTS)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [205]:
np.dot(mat1,mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [206]:
#TRANSPOSE MAT1
mat1.T

array([[5, 3, 3, 4, 8],
       [0, 7, 5, 7, 8],
       [3, 9, 2, 6, 1]])

In [210]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [212]:
mat3=np.dot(mat1,mat2.T)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [213]:
mat3.shape

(5, 5)

# exercise:  nut butter store sales

In [234]:
np.random.seed(0)
# no.of jars sold
sales_amounts=np.random.randint(29, size=(5,3))
sales_amounts

array([[12, 15, 21],
       [ 0,  3, 27],
       [ 3,  7,  9],
       [19, 21, 18],
       [ 4, 23,  6]])

In [235]:
# create weekly_sales dataframe
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon","Tues","Wed","Thurs","Fri"], 
                            columns=["Almond_butter","Peanut_butter","Cashew_butter"])
weekly_sales

Almond_butter  Peanut_butter  Cashew_butter
Mon               12             15             21
Tues               0              3             27
Wed                3              7              9
Thurs             19             21             18
Fri                4             23              6

In [236]:
# create prices array
prices = np.array([10,8,12])
prices, prices.shape

(array([10,  8, 12]), (3,))

In [240]:
# create butter price dataframe
butter_prices=pd.DataFrame(prices.reshape(1,3),index=["prices"],
             columns=["Almond_butter","Peanut_butter","Cashew_butter"])
butter_prices

Almond_butter  Peanut_butter  Cashew_butter
prices             10              8             12

In [243]:
prices

array([10,  8, 12])

In [333]:
sales_amount, sales_amount.shape

(array([[12, 15, 21],
        [ 0,  3, 27],
        [ 3,  7,  9],
        [19, 21, 18],
        [ 4, 23,  6]]),
 (5, 3))

In [246]:
# shapes arent aligned lets trasnpose
total_sales = prices.dot(sales_amount.T)
total_sales

array([492, 348, 194, 574, 296])

In [247]:
# create daily_sales
butter_prices

Almond_butter  Peanut_butter  Cashew_butter
prices             10              8             12

In [248]:
weekly_sales

Almond_butter  Peanut_butter  Cashew_butter
Mon               12             15             21
Tues               0              3             27
Wed                3              7              9
Thurs             19             21             18
Fri                4             23              6

In [249]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [251]:
weekly_sales.T.shape

(3, 5)

In [256]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales, type(daily_sales), daily_sales.shape

(        Mon  Tues  Wed  Thurs  Fri
 prices  492   348  194    574  296,
 pandas.core.frame.DataFrame,
 (1, 5))

In [257]:
weekly_sales.shape

(5, 3)

In [ ]:
# doesnt works, not the right shape
weekly_sales["Total ($)"] = daily_sales
weekly_sales

In [259]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond_butter  Peanut_butter  Cashew_butter  Total ($)
Mon               12             15             21        492
Tues               0              3             27        348
Wed                3              7              9        194
Thurs             19             21             18        574
Fri                4             23              6        296

## comparison operators

In [260]:
a1, a2,a3, a4

(array([1, 2, 3]),
 array([[1.  , 2.5 , 3.  ],
        [4.01, 5.  , 6.  ]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]]),
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]))

In [263]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [266]:
bool_type = a1>=a2
bool_type

array([[ True, False,  True],
       [False, False, False]])

In [269]:
type(bool_type), bool_type.dtype

(numpy.ndarray, dtype('bool'))

In [273]:
a1>1

array([False,  True,  True])

In [274]:
a1<5

array([ True,  True,  True])

In [275]:
a1 == a1

array([ True,  True,  True])

In [276]:
a1 == a2

array([[ True, False,  True],
       [False, False, False]])

## sorting arrays

In [289]:
random_array = np.random.randint(10, size=(3,5))
random_array

array([[0, 4, 7, 3, 2],
       [7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4]])

In [290]:
random_array.shape

(3, 5)

In [291]:
np.sort(random_array)

array([[0, 2, 3, 4, 7],
       [0, 0, 2, 4, 7],
       [4, 5, 5, 6, 8]])

In [292]:
np.argsort(random_array)

array([[0, 4, 3, 1, 2],
       [2, 3, 1, 4, 0],
       [4, 0, 1, 2, 3]], dtype=int64)

In [296]:
a1

array([1, 2, 3])

In [295]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [298]:
np.argmin(a1),np.argmax(a1)

(0, 2)

In [299]:
random_array

array([[0, 4, 7, 3, 2],
       [7, 2, 0, 0, 4],
       [5, 5, 6, 8, 4]])

In [303]:
np.argmax(random_array, axis=0)

array([1, 2, 0, 2, 1], dtype=int64)

In [304]:
np.argmax(random_array, axis=1)

array([2, 0, 3], dtype=int64)

# TURN IMAGES INTO NUMPY ARRAYS

x=![Panda Image](images/panda.png)

In [317]:
#<img src="image/pannda.png"/>

In [318]:
#turn an image into a numpy array
from matplotlib.image import imread
panda = imread("images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [320]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [321]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

In [329]:
<img src="images/car-photo.png"/>

SyntaxError: invalid syntax (4202550140.py, line 1)

y= ![Car Image](images/car-photo.png)

In [324]:
car = imread("images/panda.png")
print(type(car))

<class 'numpy.ndarray'>


In [325]:
car

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [326]:
car[:1]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]]], dtype=float32)

In [327]:
dog = imread("images/dog-photo.png")
print(type(dog))

<class 'numpy.ndarray'>


In [331]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)